# This is a basic workflow to help you get started with Actions
name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  triggered-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print client payload
        run: |
          echo "Event Type: ${{ github.event.action }}"
       
